version: 2
jobs:
  test-php80:
    docker:
      - image: circleci/php:8.0-cli
      - image: redis
      - image: rabbitmq
      - image: postgres:alpine
        environment:
          POSTGRES_PASSWORD: root
          POSTGRES_USER: root
          POSTGRES_DB: commands

    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Run tests / Symfony 5^0
          command: |
            composer update -n --prefer-dist --no-suggest
            sh .circleci/start_base_testsuite.sh

  test-php81:
    docker:
      - image: cimg/php:8.1
      - image: redis
      - image: rabbitmq
      - image: postgres:alpine
        environment:
          POSTGRES_PASSWORD: root
          POSTGRES_USER: root
          POSTGRES_DB: commands

    working_directory: ~/project
    steps:
      - checkout

      - run:
          name: Run tests / Symfony 5^0
          command: |
            composer update -n --prefer-dist --no-suggest
            sh .circleci/start_base_testsuite.sh

workflows:
  version: 2
  test:
    jobs:
      - test-php80
      - test-php81
